== プログラマーと防疫
'''

健康維持に対する最も身近で最大の障害は風邪を始めとした感染症です。本章では風邪の予防、風邪からの回復に関する方法を紹介します。

=== 風邪の予防

まず風邪予防の第一は何と言っても手洗いとうがいです。手洗いには石鹸を用いましょう。うがいには真水や塩水ではなくイソジンがオススメです。

手洗いの基本は石鹸で浮き上がらせて水で洗い流すことです。除菌成分は必須というわけではありません。近年、手洗い用石鹸に含まれる除菌剤による環境負荷、耐性菌発生のの原因とも疑われています。傷口を処置する際や抵抗力の弱い乳幼児や老人に接するのでなければ、家庭で積極的に除菌・殺菌を謳う手洗い用石鹸を使う動機はありません。

一方でうがいにはイソジンをオススメします。もともと喉から気管支が弱い筆者は、大抵は仕事帰りの最低一日一回、イソジンを用いてうがいをするようになってから、目に見えて喉のトラブルが減りました。イソジンは正確にはポピドンヨードという成分に薬効があります。これはヨード、すなわちヨウ素の酸化作用で細菌のタンパク質合成を阻害することで殺菌します。効果を発揮するのはうがいを開始してから30～60秒ほどなので、心持ち長めにうがいを実施すると効果的でしょう。もしくはうがい後少し時間をおいてからゆすぐのも良いかもしれません。

風邪の予防には前髪を長くし過ぎないことも効果がありそうです。筆者の場合は、前髪が伸びてきて目にかかりだす頃に目が炎症し、そこから鼻、喉と炎症を広げて風邪に至ることが頻繁にありました。これは髪の毛には外出時に意外と多くのウィルスや菌などが付着し、それが毛先の入った目から感染を広げていたと考えられます。筆者は長くなった前髪だけを自分で切ってしまうことで対応しています。

手洗い、うがい、適度な長さの前髪、いずれも衛生こそが予防の第一歩となります。

=== 風邪からの回復

とはいえ風邪を引いてしまうことはあるでしょう。そんな時にどうすればより早く回復するのか、考えたことはあるでしょうか？

そもそも風邪とはどういう生理的な状況なのか考えてみましょう。先にも少し書きましたが、風邪とはウィルスや菌による鼻や喉の炎症の総称です。この炎症が気管支に到達すれば気管支炎ですし、さらに悪化して肺にまで到達すれば肺炎となります。

炎症とはウィルスや菌を排除する免疫反応の一部です。鼻や喉の粘膜が炎症すると、鼻水や痰が分泌されます。これらの粘液にはウィルスや菌を絡め取り感染が広がるのを防止する機能があると考えられます。そしてそれらを異物として排出するために咳が発生します。これらがいわゆる風邪の諸症状です。

この炎症の広がりを食い止めることが風邪からの回復にとっては肝要です。正確に言うならば原因となっているウィルスや菌の排除こそが風邪が治るということです。この観点で見ると市販薬はあまり大きな効果を挙げられません。鼻水や痰の分泌を少なくしたり、熱を下げたりはできます。また炎症の反応を抑えることもできます。しかし一方でそれらの反応はウィルスや菌の完成拡大を食い止め排除するためのものですから、それを阻害してしまうことは治りを悪くしているとも捉えることができます。

これは市販薬を使うなと言っているわけではありません。症状を抑えることで存分に休息・睡眠できるならば効果的であるとも考えられます。最終的にウィルスや菌を排除するのは人体の免疫に頼らざるをえません。そして免疫力を存分に発揮するには十分な栄養と休息が必要です。風邪の諸症状がそれらを阻害するならば、なんらかの薬で緩和することが大事になります。

以上から風邪を引いた時に市販薬を飲んで誤魔化しつつ働くというのは、最も忌避すべき愚行と断じねばなりません。若いうちは免疫力も強いのでなんとかなるかもしれませんが、老いてくるとそうも行きませんし若くても何かが少し狂えば取り返しの付かないことになる可能性がゼロではありません。風邪を引いた際はしっかりと栄養と休息をとりましょう。

=== 乾燥対策

人体にとって乾燥というのは予防においても回復においても大敵となります。乾燥することで皮膚や粘膜の保護機能が低下し、そこから感染・炎症を起こし拡大することに繋がります。とは言え、加湿器を使えば良いというほど単純ではありません。加湿器を多用した結果、居室にカビを発生させそれに感染しては元も子もありません。

実は人体には鼻という優秀な加湿機構が元から備わっています。鼻を通じて吸った空気は鼻腔の粘膜により適度に加湿され、喉や気管支にウィルスや菌が到達する確率を下げます。さらに喉や気管支の粘膜が乾燥することを防ぎ、感染しにくい状態を保つのにも役立ちます。

それを踏まえると普段から鼻呼吸をすることは健康維持にとって大きな意味を持ちます。筆者は子供の頃から鼻づまりで口呼吸をする癖が付いていました。結果的に風邪を引きやすい状態だったと考えられます。比較的最近このことに気が付き、意識して鼻呼吸をするようにしました。それ以降、喉から始まるトラブルは大幅に減ってきたようです。また副作用として鼻づまりも以前に比べて改善しています。鼻を加湿器官と考えるならばそこには大量の水分が供給されており、鼻呼吸により蒸散を促さなければその水分で粘膜が膨れ上がり、空気の通り道を塞いでしまうということかもしれません。

肌の乾燥については、ワセリンなどの耐乾燥薬品を早め早めに塗布し、それ以上の刺激を避けることが重要なようです。個人的にはメンソレータムADを愛用しています。
