== プログラマーと姿勢
'''

プログラマーは長時間同じ姿勢を維持しがちです。それによるトラブルを抱えているプログラマーは少なくないでしょう。しかしそれらはちょっとしたことで避けられます。その方法を紹介します。

=== ワークチェア

プログラマーは長時間座って仕事をします。座った姿勢にとって何よりも大事なのは、頭から首と背骨にかけてまっすぐに腰骨へ体重が乗るようにすることです。そのような状態を保つのにはワークチェアによる補助がとても有効です。

そのようなワークチェアはいくつもありますが、特に有名なのはやはりハーマンミラーのアーロンチェアでしょう。筆者も腰痛になりかけた際に導入し長らく愛用していました。そして確かに定常的な腰痛には至らずに済みました。20年前でも約12万円とかなり高めの値段設定ではありますが、非常に頑丈で長く使えるため決して損はしないとオススメできます。筆者のアーロンチェアのレビュー記事は以下のURLでご覧になれます。

<https://www.kaoriya.net/articles/HowDoYouLikeAeronChair/>

ただし筆者が10年以上愛用したアーロンチェアにも欠点はあります。座面がメッシュのため座った際の張力でとても硬くなるのです。それによりお尻の筋肉が少なくなると圧迫により血行が阻害され、お尻から太ももにかけての痛みや足先のむくみの原因になりました。

そこで筆者が乗り換えた先は、またしてもハーマンミラーのエンボディチェアです。20万前後とアーロンチェアよりも更に高い価格設定ですが、しっかりと自分の身体に合わせて調整すると独特のサポート機構により、正しい姿勢の維持がアーロンチェアよりも遥かに楽に行なえます。

ワークチェアを買う際は必ず試座することを強くオススメします。安くはない買い物ですし、カタログスペックだけで身体に合わないチェアを買ってしまっては意味がありません。加えてワークチェアはサイズが大きくて設置場所だけではなく、搬入経路にも注意を払うと良いでしょう。また重量もあるので床を選ぶことには注意してください。それらを確認するためにも実物をしっかりと見ることはとても重要です。

最後にワークチェアを利用する際の注意点として、リクライニングにはまったく適さないことを付記しておきます。誤ってワークチェアに座ったまま寝てしまった日には、内臓や骨格に少なくないダメージを追うことになるでしょう。疲れたらワークチェアを離れてしっかりと休むことが重要です。

=== モニターとキーボード

プログラマーは業務とプライベート問わず長時間モニターとキーボードに向き合います。よってそれにコストをかけ良いものを利用することは、非常に高いコストパフォーマンスを発揮します。

モニターは視線を正面からやや下に落としたあたりに置くのが最も良いとされています。また距離は手がとどかないくらいに離すことが重要です。キーボードは手首や肩がリラックスした状態で使えるように配置します。またタイピングが確実にできるものを選ぶと良いでしょう。キーを押した感触が安定しないものや、押したにもかかわらず入力されないことがあるものは避けましょう。

参考までに筆者の環境を紹介します。

モニターはCRTの時代からEIZO(旧nanao)のものを使っています。CRT時代から変わらず安定した表示・発色なのもありますが、液晶時代になってからもそれは損なわれずレイアウトも変わらず調整しやすいのです。

キーボードはマイクロソフトのエルゴノミクスキーボードから始まり、この10年以上は HHKB Pro 2 に落ち着いています。HHKB は小さくてともすれば逆に疲れるように思えるのですが、最初にエルゴノミクスキーボードで正しいタイピング姿勢を身に着けたからか、何の苦もなく使い続けられています。

なおノートPCは正しい姿勢を維持するという意味では最悪と言わざるをえません。どうしても目線と頭が下がり首に負担をかけるだけでなく、トラックパッドのために手首が締まり肩にまで負担がかかります。長時間使う際には外部モニターとキーボードの両方、もしくはどちらかを接続して正しい姿勢を取ることを強く推奨します。
