== プログラマーと交互浴
'''

交互浴と言う入浴法を聞いたことはあるでしょうか？温かいお風呂と冷たい水風呂に交互に浸かることにより、自律神経系を刺激してその調整能力の回復を図る入浴方法です。

=== 自律神経系

自律神経系は交感神経系と副交感神経系の2つの神経系で構成されています。交感神経系はストレス状態を司り血圧の上昇や心拍数の増加につながるのに対し、副交感神経系はその逆でリラックス状態を司り血圧の低下や心拍数の現象につながります。またそれぞれいろいろな臓器のさまざまな活動に関わっています。

プログラマーという職業は極度の集中状態を長時間維持するにとどまらず、場合によっては昼夜を問わずそれを継続してしまう傾向があります。そのようなことを続けていると自律神経系が乱れ、休むべき時に休めず、ついにはいろいろな臓器の活動に不調をきたします。

交互浴はそのように乱れた自律神経系をリセットし、正しく機能することを狙った入浴方法なのです。

=== 交互浴の方法

交互浴の方法はとても簡単です。水風呂のある銭湯等に行き、温かいお風呂と冷たい水風呂をひたすら交互に何度も浸かるだけです。体感的には最低でも3セット、できれば5セットは行いたいです。サウナを交えるのも良いでしょう。入るべき時間は体調や風呂の温度により異なりますが、温かいお風呂を10分、冷たい水風呂を5分くらいを目安にすると良いでしょう。そしてこれがなにより重要なのですが、最後は必ず水風呂でなければなりません。

水風呂を最後にすると身体が冷えてしまうと考えるかと思います。しかし正しい交互浴により自律神経系が整っていれば、水風呂で冷やされたことで身体が自発的に発熱し始め、長く暖かさが維持されます。また長時間お湯に使っても湯上がりにのぼせる確率が減らせます。

=== オススメの銭湯

筆者は去年後半からほぼ毎週、金曜日の仕事が終わった後に交互浴をするために銭湯に立ち寄っています。お気に入りなのは銀座線は稲荷町駅のそばにある寿湯です。寿湯には通常のお風呂の他にサウナが2種、水風呂が2種、そして露天風呂があります。これでサウナ利用料にレンタルタオル代込みで710円ですから、破格の安さと言って良いでしょう。

寿湯はこれだけでも面白い銭湯なのですが、さらに浅草に近いという土地柄からか、入れ墨客を断っていない点も興味深いです。そのため時間帯によっては外国人旅行客や若者のライトなファッション入れ墨から、明らかにその筋のド迫力な彫り物など普通では見られないものが見られます。とはいえジロジロ見るのは失礼にあたりますから、自然に振る舞うようにしましょう。

また都内ということでは鶯谷にあるひだまりの泉萩の湯もオススメです。お湯の種類が豊富でじっくりと味わえるだけではなく萩の湯はビルが丸ごと銭湯になっており、ロビーフロアには食堂が併設されています。まるでスーパー銭湯のような充実ぶりですが、寿湯と同じようにサウナとレンタルタオル込みで710円で楽しめます。

そして冷たい水風呂が苦手という方には西日暮里の斉藤湯をオススメします。斉藤湯の水風呂は温度調節されており、冷たすぎず温すぎずという絶妙の加減でいくらでも入っていられます。先の2件とは異なりサウナがなく、買い取りのタオルはありますがレンタルタオルはありません。注意が必要です。
